name: Staging Tests & Build

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_COMPANY_URL: ${{ vars.VITE_COMPANY_URL }}
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist
          retention-days: 1

  test:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Restoration
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: dist

      - name: Serve Production Build
        run: |
          npx serve -s build -l 3000 &
          npx wait-on http://localhost:3000
        env:
          CI: true

      - name: Run Cypress Tests
        run: npx cypress run --browser chrome
        env:
          CI: true
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_COMPANY_URL: ${{ vars.VITE_COMPANY_URL }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: |
            cypress/screenshots
            cypress/videos
          retention-days: 1
